CREATE TABLE "electionx_candidates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electionx_candidates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"regionId" integer NOT NULL,
	"number" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electionx_regions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electionx_regions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"totalStations" integer NOT NULL,
	"totalRepresentatives" integer DEFAULT 6 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electionx_stations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electionx_stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"regionId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electionx_votes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electionx_votes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidateId" integer NOT NULL,
	"stationId" integer NOT NULL,
	"voteCount" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "electionx_candidates" ADD CONSTRAINT "electionx_candidates_regionId_electionx_regions_id_fk" FOREIGN KEY ("regionId") REFERENCES "public"."electionx_regions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "electionx_stations" ADD CONSTRAINT "electionx_stations_regionId_electionx_regions_id_fk" FOREIGN KEY ("regionId") REFERENCES "public"."electionx_regions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "electionx_votes" ADD CONSTRAINT "electionx_votes_candidateId_electionx_candidates_id_fk" FOREIGN KEY ("candidateId") REFERENCES "public"."electionx_candidates"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "electionx_votes" ADD CONSTRAINT "electionx_votes_stationId_electionx_stations_id_fk" FOREIGN KEY ("stationId") REFERENCES "public"."electionx_stations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "candidate_name_idx" ON "electionx_candidates" USING btree ("name");--> statement-breakpoint
CREATE INDEX "candidate_region_idx" ON "electionx_candidates" USING btree ("regionId");--> statement-breakpoint
CREATE INDEX "candidate_number_idx" ON "electionx_candidates" USING btree ("number");--> statement-breakpoint
CREATE INDEX "region_name_idx" ON "electionx_regions" USING btree ("name");--> statement-breakpoint
CREATE INDEX "station_name_idx" ON "electionx_stations" USING btree ("name");--> statement-breakpoint
CREATE INDEX "station_region_idx" ON "electionx_stations" USING btree ("regionId");--> statement-breakpoint
CREATE INDEX "vote_candidate_idx" ON "electionx_votes" USING btree ("candidateId");--> statement-breakpoint
CREATE INDEX "vote_station_idx" ON "electionx_votes" USING btree ("stationId");